#
###################################
# Site wide configuration
####################################
#
title:       "txt.earth"
name:        "txt.earth"
description: "だれかのエッセイ"
url:         "https://txt.earth"

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Tokyo
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title
gems: [jekyll-paginate,classifier-reborn]
      
pagination: true
paginate: 5
paginate_path: "page:num"

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: MASATOMO KUSUNOKI
  job: ""
  bio: ""
  email: kusutomo@photoantenna.com
